### ISSUE TITLE
Read only dashboard shouldnt have buttons displayed

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1015]
# Expected behavior
Read only dashboard shouldnt have . buttons such as create pipelinerun
They should be grayed out / removed 
Also shouldn't be allowed to access import resources as its read only 

# Actual behavior
Read only can click buttons 
Can go on pages like import resources 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

Read only 

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
Yeah, +1 on this, I think not having the buttons (free up screen space) and perhaps displaying the level of permissions on the About page would be excellent

**Comment by a-roberts** [comment]
I'll work on this, we could have a readonly label added to our read-only kustomization, pick this up piggybacking off @CarolynMabbott's changes to `cluster.go`, display the read-only value on the About page and then, when we load a page that's considered one allowing mutable operations, optionally display the batch action or not.

For the final point above ^^ my "good software developer hat" suggests we'd add some sort of annotation to our containers or components so that if read-only is detected, batch actions aren't added 🤔
