### ISSUE TITLE
Dashboard has no validation on length of username / password

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1029]
# Expected behavior
Should bring up error in modal saying secret is too long rather than a post error when username / password is beyond the limit of length 

# Actual behavior
POST error with a bad error / not a good human readable error returned 

# Additional Info
<img width="880" alt="Screenshot 2020-02-07 at 11 59 11" src="https://user-images.githubusercontent.com/32342288/74028020-4be3bd00-49a1-11ea-946a-4df91e6708d0.png">

<img width="682" alt="Screenshot 2020-02-07 at 11 59 17" src="https://user-images.githubusercontent.com/32342288/74028026-500fda80-49a1-11ea-9b4f-214b80660912.png">

**Comment by AlanGreene** [comment]
So the limit is 1MB for the total Secret size, which is the equivalent of someone pasting in a few whole novels into the text fields.

Since this is unlikely to happen often in practice, and we do at least catch and display the error so things don't break in case someone accidentally pastes in a load of bad content, I'm closing this issue.

Happy to revisit though.
