### ISSUE TITLE
Use X-Frame-Options header to prevent Clickjacking

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1045]
Dashboard should set the X-Frame-Options header in order to prevent "Clickjacking", also known as a "UI redress attack", in which an attacker uses multiple transparent or opaque layers to trick a user into clicking on a button or link on another page when they were intending to click on the top-level page. 

IBM staff can find more details via https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/3.

**Comment by AlanGreene** [comment]
This header should only need to be set on the root URL (that serves index.html) since all client side routes are just fragments added to that URL, e.g. `<path_to_root>/#/pipelines`, `<path_to_root>/#/about`

Unless we expect the UI to be embedded in an iframe anywhere we should just set the value to "deny"
