### ISSUE TITLE
Change Namespace when viewing PipelineRun error

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#1070]
# Expected behavior
When viewing the logs of a PipelineRun in Namespace `a`, I expect to be able to change the Namespace dropdown to navigate to Namespace `b` without seeing an error.

# Actual behavior
When viewing the PipelineRun logs from Pipeline0 in the `tekton-pipelines` Namespace, I changed the Namespace dropdown to `default`. Then, I got the following error message:

![Screen Shot 2020-02-18 at 3 14 56 PM](https://user-images.githubusercontent.com/16961496/74774311-723b0f80-5261-11ea-836f-28211c3841b4.png)

The URL was changed to `https://<MY_DASHBOARD.com>/#/namespaces/default/pipelineruns/pipeline0-run-1582056739537`.

# Steps to reproduce the problem

1. Import Tekton resources & view PipelineRun logs (in Namespace `tekton-pipelines`)
2. Select a Namespace other than `tekton-pipelines` from the Namespace dropdown

# Environment
- Kubernetes Platform: OpenShift

- Tekton Pipelines version: 0.10.1

- Tekton Triggers version: master

- Tekton Dashboard version: master

**Comment by AlanGreene** [comment]
This seems to be expected behaviour since Pipeline0 doesn't exist in the default namespace. This is the same experience as if you followed a link directly to `/namespaces/default/pipelineruns/this-pipeline-run-does-not-exist`

We could possibly change the behaviour for this specific case (changing namespace in the dropdown while on the details page) to return to the PipelineRuns list. The updated designs don't actually have the namespace dropdown on the details pages at all, avoiding this problem.

**Comment by ncskier** [comment]
Ok, good to know. It's definitely not a big problem. However, it was a little jarring as a user to see that error message.

**Comment by AlanGreene** [comment]
Yes definitely, it's good feedback. What were you originally expecting to happen when you switched namespaces? We might be able to improve this in the short term before the new designs are implemented.

**Comment by ncskier** [comment]
If I recall correctly, I was planning on navigating to the PipelineRuns list for the `default` Namespace. So, my thought process was that I would:
1. Change the Namespace to `default`
2. Click on the PipelineRuns navigation menu item

So, I actually didn't expect anything to happen 😅 I was planning on navigating to the PipelineRuns list page next.
