### ISSUE TITLE
unable to recognize "https://github.com/tektoncd/dashboard/releases/download/v0.5.1/tekton-dashboard-release.yaml": Unauthorized

### ISSUE THREAD

**Issue by codersofthedark** [tektoncd/dashboard#1115]
# Expected behavior
Dashboard should have got installed
# Actual behavior
Error: unable to recognize "https://github.com/tektoncd/dashboard/releases/download/v0.5.1/tekton-dashboard-release.yaml": Unauthorized
# Steps to reproduce the problem

1. Run: kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.5.1/tekton-dashboard-release.yaml

# Environment
- Kubernetes Platform: kubernetes cluster via kops version 1.15.10

- Tekton Pipelines version: v0.10.1

- Tekton Triggers version: NA

- Tekton Dashboard version: v0.5.1

**Comment by AlanGreene** [comment]
I just verified in a few environments (OCP, iKS, and Docker desktop) that the release is working as expected using the same URL.

From a quick search of the error message is seems like this may be due to some misconfigured auth settings on your cluster, or missing / invalid auth settings in your kubeconfig.

Can you verify you're targeting the expected context (`kubectl config current-context`)?
Do other `kubectl` commands succeed against the same cluster?
It might be worth reviewing `kubectl config view` to see if it's as expected (correct users, tokens, etc. specified).

**Comment by AlanGreene** [comment]
@codersofthedark did you manage to resolve your issue? I'm closing this since I don't think there's anything to do on the dashboard side, we can reopen if that's not the case.
