### ISSUE TITLE
User should be able to link directly to list of access tokens

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1121]
# Expected behavior
A user should be able to follow a link directly to view a list of access tokens (including filters for namespace etc.) as with other resource types.

# Actual behavior
The access tokens are hidden behind a radio button selection on the secrets page and this selection is not reflected in the URL.

# Additional Info
https://github.com/tektoncd/dashboard/pull/1117#pullrequestreview-369695300

**Comment by a-roberts** [comment]
Yeah, so to confirm - for this one instead of thinking of a specific resource page, clicking on the access tokens link should change the URL to include a filter by type=accesstoken right? Then there's a programmatic way for anyone to easily see all of the access tokens (instead of rendering the page then clicking said button), they'd just know the tokens can be found at X location

**Comment by AlanGreene** [comment]
it was still showing up in queries for open issues
