### ISSUE TITLE
Super flaky test: CreatePipelineRun

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1167]
# Expected behavior
Should pass reliably

# Actual behavior
Fails repeatedly, see https://github.com/tektoncd/dashboard/pull/1166

# Steps to reproduce the problem
src/containers/CreatePipelineRun/CreatePipelineRun.test.js

**Comment by AlanGreene** [comment]
Finally managed to get this to fail locally:

```bash
$ count=1; while npm run test:ci; do (( count++ )); done; echo "Failed on run $count"
```

Getting <5% failure (i.e. less than 1 in 20 runs), not sure why it's so difficult to reproduce locally or why it seems to latch onto one PR (e.g. https://github.com/tektoncd/dashboard/pull/1172) and fail repeatedly for a while before just disappearing again.

Reviewing the tests in more detail now to see if we can restructure them to get more info on the failures or if we can avoid these entirely.

**Comment by AlanGreene** [comment]
Taking another looks at this now

**Comment by AlanGreene** [comment]
Think I have something, running in a loop now to 'verify' (as much as we can given how intermittent this has been...) 🤞

**Comment by AlanGreene** [comment]
OK so I've had the full set of tests running in a loop for over 2 hours now (>200 iterations) with no failures. I did manage to get the tests to fail >50% locally by switching the tests to use the redux-connected container so I'm pretty confident at this stage that the issue is resolved.

The reason I switched to the container is to ensure consistency between the data being retrieved from the store by the dropdowns and the props passed in the tests, they were out of sync in a few places.

🔍 Here's the 'interesting' part, the main cause for the failures...
Carbon adds a hidden element on the page for modals / dropdowns that acts as a 'status' element for screen readers, announcing certain types of change or interaction on the page. Depending on timing or the order of test execution / interaction, this status element sometimes happens to contain the pipeline / namespace name we're expecting to find in an opened dropdown. Triggering a click on the matched element ends up clicking on this status element instead of the dropdown, so I've updated the tests to target the dropdown by title instead.
