### ISSUE TITLE
Error loading secrets page: cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#1240]
**Problem:**
After clean install of Tekton I get `Error loading page Cannot read property 'accessToken' of undefined` when selecting Secrets > Access Token
Note that when selecting Secrets, it take a 

**Versions:**
Pipelines v0.10.1,  Triggers 0.3.1, Dashboard and webhooks v0.5.3
OCP 4.4RC1

**Steps to reproduce:**
1. Install Tekton using version indicated above
2. Click the Secrets Tab
3. Click the Access token radio button
4. Error message is presented and the expected UI is not rendered.
5. Click the About tab or any other tab
6. Click secrets tab and Access token radio button again
7. The same error is displayed

**Workaround:**
1. Click secrets tab
2. Create a secret using the Password radio button UI
3. Click the about tab or any other tab
4. Click Secrets tab
5. Select the Access Token radio button
6. This time the expected UI is rendered

**Comment by a-roberts** [comment]
Yeah definitely seeing with the 0.6.1 release candidate on OpenShift, not on Docker Desktop

**Comment by a-roberts** [comment]
Gonna bet this is due to existing secrets (on OCP, in the install namespace) not having .accessToken then, see 
![image](https://user-images.githubusercontent.com/12814972/78885038-cee1cc00-7a53-11ea-94fe-4f6bc0742da8.png)

and we need an if defined check, so the forEach is likely https://github.com/tektoncd/dashboard/blob/master/src/containers/Secrets/Secrets.js#L240

**Comment by a-roberts** [comment]
Merged so closing
