### ISSUE TITLE
Use X-XSS-Protection Header

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#1250]
X-XSS-Protection header is not used in the dashboard. The "X-XSS-Protection" header forces the CrossSite Scripting filter into Enable mode, even if disabled by the user. This filter is built into most recent web browsers (IE 8+, Chrome 4+), and is usually enabled by default. Although it is not designed as first and only defence against Cross-Site Scripting, it acts as an additional layer of protection. 

IBMers with sufficient access can refer to https://github.ibm.com/IBMCloudPak4Apps/icpa-security/issues/38 for more information.

**Comment by AlanGreene** [comment]
X-XSS-Protection is considered flawed and obsolete, the recommendation is generally to use Content-Security-Policy instead (tracked in https://github.com/tektoncd/dashboard/issues/1049).

Chrome removed their XSS Auditor (which was controlled by the X-XSS-Protection header) in version 78
https://www.chromestatus.com/feature/5021976655560704

Firefox has stated no intention to support this header
https://bugzilla.mozilla.org/show_bug.cgi?id=528661

Edge retired their XSS filter in 2018, and have since rebased the browser on Chromium
https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/

I propose closing this and focusing on the CSP header instead.

**Comment by mnuttall** [comment]
Sounds good, let's do that.
