### ISSUE TITLE
Import resources using self-contained pipeline run ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1257]
https://github.com/tektoncd/dashboard/blob/ef5e0a574bcd0b77a563d51e9be7886f60d5b89e/src/containers/ImportResources/ImportResources.js#L161-L241

Wouldn't it be better to use a pipeline run with embedded resource spec, pipeline spec and task spec (thus creating a self contained pipeline run) instead of relying on multiple resources and pre existing pipeline/task ?

**Comment by AlanGreene** [comment]
Yes I think this makes sense, and it has previously been discussed in https://github.com/tektoncd/dashboard/issues/469

At the time we were waiting for Pipelines to support `resourceSpec`, but since it does now I think we should be able to go ahead with it.

@a-roberts any concerns? Any impact on Kabanero if we modify / potentially remove `pipeline0`?

**Comment by eddycharly** [comment]
Ok, i will wait a little to be sure everyone is ok and will take care of it. 

Thanks.

**Comment by a-roberts** [comment]
Nope no concerns, it's definitely a good change to make 👍

**Comment by eddycharly** [comment]
👍 
/assign

**Comment by AlanGreene** [comment]
Merged and included in latest nightly, closing. Thanks @eddycharly!

/close
