### ISSUE TITLE
Add Tekton Dashboard roadmap.md (and link to community one)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1266]
See https://github.com/tektoncd/community/pull/77#issuecomment-603324351, and under the same PR you can see your at the time approved roadmap items - so this one could do with revisiting and getting in here

**Comment by AlanGreene** [comment]
> @vdemeester for the Dashboard here's what I'm personally thinking would be useful to have, I'd  like to get input from @mnuttall and @AlanGreene before we commit to anything in particular
>
> 1) Observability (which Trigger resulted in which PIpelineRun or TaskRun)

✅ Strong +1. It should be easy for a user to navigate between related resources for more details as well as surfacing some info directly in the PipelineRun and TaskRun views

> 2) Currency (latest Pipeline and Trigger versions)

✅ Strong +1. Currently missing sidecars, retries, better display of conditions, results, Task details on TaskRun/PipelineRun view. We should probably call out at least a few of these explicitly.

> 3) Performance through pagination and sorting (thanks to @afrittoli's dogfooding cluster we know we need this)

❓ This one's tricky. Our current use of the Kubernetes APIs means we can't easily add either pagination or sorting unless we want to do it client side which doesn't help on very busy clusters. How do we feel about 'show more'-style chunking (which is supported by the kube APIs) combined with additional filtering capabilities? It would help to understand the pain points / use cases we're trying to address, perhaps the work around '1. Observability' will be sufficient for some of them.

> 4) Visualisations (@AlanGreene has some excellent work in this area already)

⏳ Yes I'd really love to see us make progress on this. Maybe we can reduce the scope a bit to get _something_ in sooner rather than later.

> 5) Platforms (e.g. known to work on various clouds)

✅ Definitely need to improve cross-platform testing. At the moment we're essentially OpenShift only since Docker Desktop isn't a production environment 😆 

> 6) Improved test story, perhaps with Selenium - something that exercises our functionality against different versions (a colleague at IBM has been making good progress on this)

✅ Ties into '5. Platforms' We need to close some of the gaps in our current test strategy as well as making it easier for devs to run all tests locally as a regular part of the development process.

> 7) Staying on top of security issues and having a documented procedure (ideally this should be across the Tekton space)

I agree this should be common across the projects, not specific to Dashboard.

>
> _Originally posted by @a-roberts in https://github.com/tektoncd/community/pull/77#issuecomment-587015851_
