### ISSUE TITLE
Intermittent error - Secret view after creation is wrong 

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1271]
# Expected behavior
I see the secrets in the namespace i just created

# Actual behavior
I see a secret in a different namespace 

# Steps to reproduce the problem

1. Go to http://localhost:9097/#/namespaces/tekton-pipelines/secrets
2. Create a secret in any other namespace 

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1

# Additional Info
<img width="1631" alt="Screenshot 2020-04-09 at 10 44 55" src="https://user-images.githubusercontent.com/32342288/78882877-a1dfea00-7a50-11ea-90c6-4c597a6e611e.png">

Might not be releated to this issue but did appear when this happenned
Seems to be intermittent error 
I get this in the console ```Uncaught (in promise) Error: Internal Server Error
    at P (main.f05bee84075259112d6f.js:1)```

On that page it updates with new secrets but only in the tekton-pipelines namespace even though default is selected but with no service accounts

**Comment by CarolynMabbott** [comment]
Can get a continuous solid reproduce by:
1. Going to : `http://localhost:9097/#/namespaces/tekton-pipelines/secrets`
2. Create a secret called `a` in `tekton-pipelines` with everything being `a` and do not patch 
3. Create s secret in `default` using everything as `a` and do not patch

**Comment by CarolynMabbott** [comment]
managed to reproduce on openshift as well as docker desktop 

/kind bug

**Comment by AlanGreene** [comment]
Discussed with Carolyn on Slack. This is another of the grab-bag of namespace related issues that keep rearing their heads. As discussed on today's Working Group call I'm gathering all of these issues together so we can get a better picture of the pain points and hopefully address them in a single consistent manner.

For this specific issue my current best suggestion would be to extract the Create Secret UI to its own page instead of having it managed as a view state of the Secrets list page. This way we could more easily address the namespace issue by removing namespace from the URL entirely, allowing the global namespace filter to be applied (the dropdown is behaving as expected, but the presence of the namespace in the URL is overriding it and causing this issue).

I think this is worth doing regardless of this issue, as it gives us the ability to link directly to the Create Secret UI and also simplifies the code in the Secrets container for the list view.

I haven't fully sized the effort but from an initial scan of the relevant code it's probably somewhere between small and medium. Happy to walk through this in more detail if we decide to pursue this as the fix, otherwise I'll open an issue to track it separately.

**Comment by AlanGreene** [comment]
it was still showing up in queries for open issues
