### ISSUE TITLE
No notification on rerun pipelinerun from pipelineruns page

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1272]
# Expected behavior
I get a notification 

# Actual behavior
I dont get a notification 

# Steps to reproduce the problem

1. Rerun a pipelienrun from the pipelineruns page
2.
3.

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

0.11.1
- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1
# Additional Info

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/issues/1178

Normally in Carbon you would not display a notification for adding an item to a table. Since you're already on the page where the item will appear this is usually considered sufficient.

If there's a long delay before the item is added, or the item will appear on a different page, then a notification is appropriate to confirm the user's action is being processed, and optionally directing them to where they can (eventually) see the new item. We do this on import, triggering a re-run from the PipelineRun page, etc.
