### ISSUE TITLE
Secrets page errors when adding a new sa like installing triggers

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1277]
# Expected behavior
It doesnt error 

# Actual behavior
It errors 

# Steps to reproduce the problem

1. Be on secrets page on all namespaces
2. Install triggers 
3.

# Environment
- Kubernetes Platform:

docker 

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1

# Additional Info
Error below is what I see 

<img width="1394" alt="Screenshot 2020-04-09 at 15 02 56" src="https://user-images.githubusercontent.com/32342288/78903658-60ad0180-7a73-11ea-99ba-77114f2dddf3.png">

**Comment by AlanGreene** [comment]
Sounds like https://github.com/tektoncd/dashboard/issues/1202 which was fixed...

How are you installing the dashboard? Is it from the prerelease or a local dev build?

**Comment by CarolynMabbott** [comment]
@AlanGreene yeah i thought it was fixed, I have installed 0.6.1 dashboard today and im still getting the error

**Comment by AlanGreene** [comment]
I haven't been able to reproduce this.

- Was this an existing environment that you updated to 0.6.1 or a clean install?
- If existing, was Triggers previously installed?
- Did you install using one of the YAML files from the pre-release at https://github.com/tektoncd/dashboard/releases/tag/v0.6.1 or build it yourself from source?

Anything else that might help to narrow it down?

**Comment by CarolynMabbott** [comment]
It was a clean install
Triggers wasnt installed previously
I installed latest of everything(pipelines,  dashboard and triggers)

**Comment by AlanGreene** [comment]
Just tried this again on a brand new environment:
- OpenShift 4.3 (CodeReady Containers 1.8)

Steps:
- Installed pipelines 0.11.1 [release.notags.yaml](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-on-openshift)
- Installed dashboard 0.6.1 [openshift-tekton-dashboard-release.yaml
](https://github.com/tektoncd/dashboard/releases/download/v0.6.1/openshift-tekton-dashboard-release.yaml)
- Open secrets page in browser
- Ensure All Namespaces is selected in the left nav
- Install Triggers 0.4.0 [latest/release.yaml](https://github.com/tektoncd/triggers/blob/master/docs/install.md#installing-tekton-triggers-1)

No errors in console, network tab, or on the page. I can navigate to the `tekton-triggers-controller` service account and see the associated secrets created as expected.

Also tested by manually creating a service account from the command line and observed the same expected behaviour.

Unassigning myself since I haven't been able to reproduce it and won't be able to test a potential fix. @CarolynMabbott @Megan-Wright if you're both able to reproduce it consistently could one of you take a look?

**Comment by CarolynMabbott** [comment]
@AlanGreene Having a look now as can reproduce 
In console I get following error:
```
Secrets.js?510b:280 Uncaught TypeError: Cannot read property 'forEach' of undefined
```
When I look at where it went wrong it's here:
`        serviceAccount.secrets.forEach(secretInServiceAccount => { `

```
const serviceAccountsWithSecret = [];
      serviceAccounts.forEach(serviceAccount => {
        serviceAccount.secrets.forEach(secretInServiceAccount => {
          if (
            secretInServiceAccount.name === secret.metadata.name &&
            serviceAccount.metadata.namespace === secret.metadata.namespace
          ) {
            serviceAccountsWithSecret.push(serviceAccount.metadata.name);
          }
        });
      });
```

**Comment by AlanGreene** [comment]
same fix as in the Secret container should do the trick so,

`(serviceAccount.secrets || []).forEach(secretInServiceAccount => {`

**Comment by a-roberts** [comment]
Let's get this one into 0.6.1 as well, thanks @CarolynMabbott and @AlanGreene
