### ISSUE TITLE
Should we default to the Tekton catalog for importing resources?

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#1328]
We've had the import resources function for a while now, and I thought of this while thinking how we can support Tekton itself and its ecosystem (so ideally there'll be a Task/Pipeline for everything, and the centralised place for them right now is the catalog, which is becoming more and more mature, and why not encourage importing from there through our Dashboard). 

It's likely therefore that the catalog's going to be the first place you'll want to import from and, at least in my case, the repository URL's never remembered or suggested and for a first time user they may be confused as to what's an ideal value to put in here.

Three ideas spring to mind

1) Defaulting the URL to be https://github.com/tektoncd/catalog
2) Either providing default folder values, or making things smarter in the sense that on choosing a URL, we'll actually do a directory lookup on the Git folder and provide auto-fill for the folder names
3) Addressing the name (Import Resources) of it so it's more obvious you should be using this for importing Tekton resources really - such as Pipelines, Tasks, etc. Yeah, technically I can be importing any old resources from yaml but the current name doesn't make it particularly obvious.

**Comment by eddycharly** [comment]
What would be really nice IMO would be a sort of wizzard guiding the user through the process.

The wizzard could propose a "Import resources from Tekton catalog" option with dedicated screens.

**Comment by AlanGreene** [comment]
1. I think it's also worth keeping an eye on the progress of https://github.com/tektoncd/hub which will provide a web UI for discovering / contributing items to a catalog.

2. I wonder if there's been any discussion about the hub exposing an API that might help here...

3. People often create PVCs, ServiceAccounts, even Namespaces along with their Tekton resources, so we should probably drop the 'Tekton' from the title. We should also review the content and structure of the page to make it more user friendly.

We also need to update Create PipelineRun / TaskRun to add support for workspaces, possibly more, and ideally we'd do this before pointing import at the catalog since workspaces are so widely used there already.
