### ISSUE TITLE
Improve About page

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1344]
It's a rainy sunday here so.. I'm playing with the about page ;-)

I made changes to split dashboard/triggers/pipeline informations, and added extensions list.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/47974576/80910186-0fb8c200-8d2e-11ea-83e0-6ac3975e258b.png)

What do you think ?

/cc @a-roberts @AlanGreene

**Comment by a-roberts** [comment]
Looks good, will raise on today's WG and let's get @AlanGreene's input

**Comment by eddycharly** [comment]
I think it makes sense to separate as we support different namespace per component through https://github.com/tektoncd/dashboard/pull/1262

**Comment by a-roberts** [comment]
> I think it makes sense to separate as we support different namespace per component through #1262

Definitely 👍

**Comment by AlanGreene** [comment]
Splitting these apart makes sense since there's more info to display for each project now 👍 

I'm not sure including the extensions here gives any additional benefit over them already being listed in the nav. Maybe in future if/when we expand their capabilities and properly document their use this could make sense but for now my vote would be to leave them out.

Here's a very simple design idea I was playing with a while back to introduce some character to the about page:
![image](https://user-images.githubusercontent.com/2829095/81057191-dc0fa080-8ec3-11ea-815b-fad322cee657.png)

(placeholder until we get our own logo: https://github.com/tektoncd/dashboard/issues/1012)

I think it would still work with multiple tables, and helps avoid the 'stretched' look with sparse tables spanning the full width.

**Comment by eddycharly** [comment]
Do you want me to open a PR with what I have or it’s useless ?

About the extension it’s useful to show the config (the resource and api group/version behind it). This doesn’t appear elsewhere.

**Comment by AlanGreene** [comment]
A PR would be good.

The extensions show the group/version/kind on master, this is not yet included in a Dashboard release but will be in the next one.
![image](https://user-images.githubusercontent.com/2829095/81058338-2a25a380-8ec6-11ea-970c-8bac9fb0d44f.png)

**Comment by eddycharly** [comment]
I'll wait for this PR https://github.com/tektoncd/dashboard/pull/1348 to be merged before creating the new one because it would conflict.
