### ISSUE TITLE
Dashboard shows timed out pipelineruns / taskruns as running

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1417]
# Expected behavior
It doesnt show them as running 

# Actual behavior
It shows them as running 

# Steps to reproduce the problem

1.
2.
3.

# Environment
- Kubernetes Platform:

Docker 

- Tekton Pipelines version:

0.12.1 

- Tekton Triggers version:

- Tekton Dashboard version:

master 

# Additional Info
This is intermittent as it shows correctly sometimes and other times does not show correctly
These were reruns 

![Screenshot 2020-05-21 at 10 26 17](https://user-images.githubusercontent.com/32342288/82544795-8edf3000-9b4d-11ea-8191-9f65e7f822a9.png)

![Screenshot 2020-05-21 at 10 26 30](https://user-images.githubusercontent.com/32342288/82544799-90105d00-9b4d-11ea-8e0a-df88912fd13f.png)

**Comment by AlanGreene** [comment]
As far as I recall this is due to the way Tekton Pipelines reports the status of the step. In some cases it doesn't get updated to reflect the fact that it was terminated.

I know there have been changes over the past few releases to address various error cases where statuses weren't being updated correctly so would need to validate whether this is still the case or if we're seeing something else here.

**Comment by CarolynMabbott** [comment]
How would I be able to tell if this is a issue with the way Tekton Pipelines reports the status of the step or something else? 
Should I be looking at the taskruns yaml or logs to find this?

**Comment by AlanGreene** [comment]
If you check the status tab you should see 'running' instead of 'terminated'.

You can verify this is not related to the dashboard by running `kubectl describe taskrun <name>` and looking at the step status being reported there.

**Comment by AlanGreene** [comment]
Fixed in pipelines 0.16.0 (PR 3088)
