### ISSUE TITLE
Recent releases not present in the release bucket

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1505]
# Describe the bug

Manifest for recent releases are not present in the bucket.
Last one is `v0.6.0`

# Expected behaviour

All released versions can be downloaded from the gcs bucket.

/cc @a-roberts

**Comment by a-roberts** [comment]
Yeah it's an interesting one, it's not done automatically, so I think we need to document this in the tekton/README.md while that's the case. I can look at uploading the release assets manually in the meantime, although personally I think having the GitHub releases as the one source of truth is sufficient. Not clear what the bucket's for really with regards to yaml... perhaps @afrittoli and @vdemeester can offer some pointers?

**Comment by AlanGreene** [comment]
Just took a look at this since I did the v0.7.1 release. It turns out the files are being uploaded, just to the wrong location.

Instead of going to `dashboard/previous/v0.7.1` in this instance they were added at `dashboard/latest/previous/v0.7.1`
`latest` shouldn't be included in the path here, so we need to update our publish pipeline to fix this, while still allowing us to target a test bucket if needed.

I'll give it a go later this week.

**Comment by AlanGreene** [comment]
Should we adopt a similar pattern to the Pipelines release? There's a `releaseAsLatest` param that controls whether the manifests also get copied into the `latest` folder: https://github.com/tektoncd/pipeline/blob/08ac72c3c4be11330d9f909b7519a4788d46ad90/tekton/publish.yaml#L20

This would allow us to run a release without updating references to `latest` if we wanted.

**Comment by a-roberts** [comment]
> Should we adopt a similar pattern to the Pipelines release? There's a `releaseAsLatest` param that controls whether the manifests also get copied into the `latest` folder: https://github.com/tektoncd/pipeline/blob/08ac72c3c4be11330d9f909b7519a4788d46ad90/tekton/publish.yaml#L20
> 
> This would allow us to run a (test/pre-)release without updating references to `latest` if we wanted.

Yeah, awesome idea and catch, +1
