### ISSUE TITLE
Dashboard JS packages size are not optimized

### ISSUE THREAD

**Issue by dankraemer** [tektoncd/dashboard#1608]
# Describe the bug
When the dashboard is initialized, the JS packages seem too big and take too long to load.
![image](https://user-images.githubusercontent.com/3615003/87071660-e49c9400-c1f0-11ea-9c99-11a07e94818b.png)

# Expected behaviour

React builder suggests some strategies to reduce JS packaging size.

**Comment by AlanGreene** [comment]
This is something we're actively working on, the most recent release 0.7.1 makes some progress in reducing the size of the static resources:
![image](https://user-images.githubusercontent.com/2829095/87079817-89819600-c21e-11ea-8483-e41ed1461e4d.png)

There are more changes to come to reduce these even further.

**Comment by AlanGreene** [comment]
Closing since this is an ongoing effort and recent releases / nightly builds have made good progress. The vendor bundle has been reduced from 5.4MB in 0.7.0 to 3.1MB in 0.7.1 and even further to 1.7MB in the latest nightly builds.

There have also been minor reductions in some of the other bundles, most notably the CSS.

Further planned improvements and optimisations are tracked in issues related to the dashboard extensions among others.

**Comment by dankraemer** [comment]
@AlanGreene, Thanks for the update!
