### ISSUE TITLE
Dashboard integration test: create a pipelinerun

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#161]
Further to https://github.com/tektoncd/dashboard/commit/f6d370645391107a2ea2e57c84f2e27f472a4f6b we have support for 'e2e' or 'integration' tests - tests that run against a deployed dashboard. 

Use this to create a first basic 'sniff' test:
- Creating a pipelinerun should make something happen - e.g. build and deploy a simple ksvc, check it's running.

**Comment by ncskier** [comment]
I spoke with @CarolynMabbott and @vtereso about the specification in this issue:
> e.g. build and deploy a simple ksvc, check it's running.

Since we are creating tests for the dashboard, which is not dependent on Knative, this test should use a sample app with a normal Service and Deployment instead of a Knative Service. This change will also simplify the work for setting up tests because we will not need to install Knative and Istio.

@mnuttall is this change alright with you?

**Comment by a-roberts** [comment]
Merged so closing 🎉
