### ISSUE TITLE
Add theming support

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1713]
This issue tracks the addition of theming support to the Tekton Dashboard.

Right now, the Tekton Dashboard uses a somewhat dark theme, it would be nice to be able to switch between light and dark themes.
Ideally, the theme chosen by the user should be recorded so that the Dashboard always show the same theme when started.

There was no previous work around this feature but i'm sure @AlanGreene will have some helpful ideas.

**Comment by AlanGreene** [comment]
The Carbon Design System which provides the base components used by the Dashboard does not currently have full theme support, not all components are fully using the Carbon colour tokens and there are issues around dynamically switching themes. The theme is built into the component styles and not easily separated. We're using [Gray 10](https://www.carbondesignsystem.com/guidelines/color/usage) with a Gray 90 side nav (one of the components that doesn't currently have proper [support for themeing](https://github.com/carbon-design-system/carbon/issues/4839)).

There's some work in progress / planned by the Carbon developers to include improved theme support for the next major release, Carbon 11. There's some experimental support today for CSS custom properties but I'm not sure if that's stable enough for production use yet.

**Comment by AlanGreene** [comment]
One of the Carbon issues tracking related changes: `https://github.com/carbon-design-system/carbon/issues/6223`

**Comment by 06kellyjac** [comment]
/remove-lifecycle stale

Theming is still important

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/dashboard/pull/2016 introduces the foundational work required to support theming (CSS custom properties), and includes some previews of how things could look based on our current design token use.

More work required to complete this but it should be a lot simpler for someone to pick up once that PR is merged.

**Comment by AlanGreene** [comment]
Dark mode is available as an experimental feature since v0.17.0 or nightly builds since 2021/05/05.

It can be enabled by setting a flag in the browser's localStorage: `localStorage.setItem('tkn-theme', 'dark')`
Alternatively, to respect the system light/dark theme settings set the value as follows: `localStorage.setItem('tkn-theme', 'system')`

Refresh the page to see the select theme take effect.

Remaining work:
- audit colour token usage to ensure correct semantic use, and display on both light and dark theme
- replace any remaining hardcoded colours with Carbon colour tokens
- review colour contrast for accessibility (minimum WCAG AA compliance)

Some examples of areas to improve in dark mode:
- link colour on tables
- placeholder text in form elements
- container of YAML tab on resource details page is same colour as page background, possibly wrong token used
- label tags on resource details page (maybe remove the additional properties for the tag component)

The above should also be checked on the default light theme of course.

**Comment by AlanGreene** [comment]
Theme settings added in https://github.com/tektoncd/dashboard/pull/2146
Respects OS settings by default and allows user to override by explicitly choosing either light or dark theme.
