### ISSUE TITLE
Sometimes PipelineRun view fails with "Error loading page  e.sort is not a function"

### ISSUE THREAD

**Issue by bkmeneguello** [tektoncd/dashboard#1723]
# Describe the bug

As far as I could understand, Condition checks sometimes don't have "status":
![image](https://user-images.githubusercontent.com/1322552/93218912-27bf3a00-f741-11ea-98b7-826dffe512db.png)

This causes the [sortStepsByTimestamp](https://github.com/tektoncd/dashboard/blob/44df2f3b16913009e2d11b76309b10ad04c83563/packages/components/src/components/TaskTree/TaskTree.js#L54) to fail and the page to be rendered as:
![image](https://user-images.githubusercontent.com/1322552/93219047-50473400-f741-11ea-8db8-b3cb24821912.png)

# Environment details

- Kubernetes Platform:
EKS
- Kubernetes or OpenShift version:
v1.16.3
- Install mode (if on OpenShift):
Operator
- Cloud-provider/provisioner:
EKS
- Versions:
   - Tekton Dashboard:
   0.9.0
   - Tekton Pipelines:
   0.15.2
   - Tekton Triggers:
   0.7.0
- Install namespaces:
   - Tekton Dashboard:
   tekton-pipelines
   - Tekton Pipelines:
   tekton-pipelines
   - Tekton Triggers:
   tekton-pipelines

**Comment by AlanGreene** [comment]
@bkmeneguello thanks for reporting and for your investigation. Is this consistently reproducible? Are you only seeing this while the PipelineRun is in progress or are you also seeing it once it's complete?

I can intermittently reproduce something similar by opening the PipelineRun details page immediately once a new PipelineRun is created and am currently testing a fix for this. Any additional information you can provide would be really helpful to confirm whether it's the same root cause.

**Comment by AlanGreene** [comment]
This should be fixed by https://github.com/tektoncd/dashboard/pull/1724 which is included in the latest nightly release. Feel free to reopen the issue with additional details if you're still seeing it.
