### ISSUE TITLE
The menu entry for Extensions for cluster-scoped CRD should always be visible

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/dashboard#1800]
# Describe the bug
We have registered a cluster-scoped CRD to the dashboard. The extension is displayed as long as the Namespace selector in the menu on the left is set to "All Namespaces" or to the namespace of the Extension CR instance.

# Expected behaviour
The menu entry for cluster-scoped resources should always be visible.

# Additional Info
This is a follow up for https://github.com/tektoncd/dashboard/issues/1731

**Comment by AlanGreene** [comment]
This should be a simple fix. We already have code in place to detect when the Dashboard is installed in single namespace mode so it should be safe to make the non-namespaced API call if the `tenantNamespace` is not set instead of falling back to the globally selected namespace from the UI.

I'll test this out now and open a PR. We'll include the fix in the release that's due in the next couple of days.

/assign

**Comment by AlanGreene** [comment]
Fix is merged, it'll be included in the next nightly build (~3am UTC) and also the next release.

/close

**Comment by AlanGreene** [comment]
Fix is available in Dashboard v0.10.2
