### ISSUE TITLE
authenication and user management in dashboard 

### ISSUE THREAD

**Issue by IamGabrielWu** [tektoncd/dashboard#1923]
# Is your feature request related to a problem ?

Now everyone has access to dashboard can do everything they want. This is not expected. I hope there could be an authentication so users need to authenicate then sign in and also I hope we can manage users with different permissions, like roles or groups.

Role User for viewing logs.
Role Admin for create taskrun/tasks/pipelines/pipelineruns -- 

# Describe the solution you'd like
We need user management && user authentication.

**Comment by AlanGreene** [comment]
Thanks for the feature request @IamGabrielWu. This is something we're already tracking in a number of issues related to authentication and more granular permissions etc. See for example:

- authentication https://github.com/tektoncd/dashboard/issues/692
- single namespace visibility https://github.com/tektoncd/dashboard/issues/1018
- run as a client via `kubectl proxy` https://github.com/tektoncd/dashboard/issues/1388
- perform actions on behalf of user (rather than using Dashboard service account permissions for everything) https://github.com/tektoncd/dashboard/issues/1420

Closing this as a duplicate.
/close
