### ISSUE TITLE
Carbon Design System Modal is not working properly with the dashboard UI Shell

### ISSUE THREAD

**Issue by ncskier** [tektoncd/dashboard#195]
# Expected Behavior
Here is the codesandbox link to a primitive example of what is expected from the Modal component: https://codesandbox.io/embed/carboncomponentsreact-7zzqn
![Screen Shot 2019-05-28 at 2 56 41 PM](https://user-images.githubusercontent.com/16961496/58504538-d4466880-8158-11e9-91b6-6d443b97e73d.png)

# Actual Behavior
There are a few things that went wrong when I tried using the Modal component in the dashboard code: 

#### 1. The header and side nav areas are not grayed out, and can be clicked without dismissing the modal view.
![Screen Shot 2019-05-28 at 2 46 13 PM](https://user-images.githubusercontent.com/16961496/58503964-a90f4980-8157-11e9-9066-39fc56830b26.png)

#### 3. When scrolling up/down the page, the modal view moves with the page. Instead, the modal view should have a fixed position, and only the content behind it should scroll.

# Steps to Reproduce the Problem

For reference, here is my branch where I mimicked the codesandbox code in the dashboard: https://github.com/ncskier/dashboard/tree/sandbox. I added a page at `http://localhost:8000/#/sandbox`.

# Additional Info
FYI @AlanGreene

**Comment by AlanGreene** [comment]
I can reproduce the same issue in a codesandbox once I load the styles for the UI Shell header + content: https://codesandbox.io/s/carboncomponentsreact-vxg18

I'd suggest checking the Carbon repo / slack to see if this is a known issue or if there's a suggested solution.

**Comment by carlos-logro** [comment]
After doing some testing here is what I have concluded:

1. The header and side nav areas are not grayed out, and the only way to make this happen is if the modal is opened within the App or index.html file. 

2. The modal is centered in the entire Content element when it should be centered in the viewport. To fix this i had to specify a viewport height by either 88.6vh or calc(100% - 7rem) 
*7rem being the height of the header*

3. When scrolling up/down the page, the modal view moves with the page. Like in the 1st answer, the only way to avoid this is by opening the modal from the App or index.html file

asked in `#carbon-react` to see what they suggest on doing for the 3rd one.

**Comment by carlos-logro** [comment]
@AlanGreene found out the reason behind this behavior & its because `<main class="bx--content">` has the style `transform: translate3d(0, 0, 0);`. I omitted it in the inspector & did not see any changes apart from the modal being viewed how we want to. I attached some pictures: 

the first one is how it currently looks. With the style mention above applied and also specifying some height & padding to the modal so it shows up in the middle of the screen.
<img width="1680" alt="Screen Shot 2019-06-03 at 4 16 16 PM" src="https://user-images.githubusercontent.com/49996607/58831652-24bb3b80-861b-11e9-8350-54f4ab62a3a3.png">

In this picture, everything mentioned above is omitted. 
<img width="1680" alt="Screen Shot 2019-06-03 at 4 15 49 PM" src="https://user-images.githubusercontent.com/49996607/58831721-4fa58f80-861b-11e9-9dc4-c0511568265b.png">

**Comment by AlanGreene** [comment]
That particular value is often used as a sort of performance hack by bumping the affected element to its own layer for GPU-accelerated animation. If interaction / animations are still smooth I'd be ok with disabling it, a note to the Carbon folks would be good as I'm sure others will hit this if they haven't already.

**Comment by carlos-logro** [comment]
awesome!! where can I contact the Carbon folks?? Ill update my modal & remove the style so it looks good when that value is disabled.

**Comment by AlanGreene** [comment]
The Carbon monorepo is at https://github.com/carbon-design-system/carbon and I see you've already mentioned the issue to them on Slack
