### ISSUE TITLE
Remove the dropdown container components from the Storybook

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#2048]
The Dashboard Storybook is intended as a development sandbox and showcase for the UI components provided by the `@tektoncd/dashboard-components` package.

These should be pure UI components, with no dependency on any particular data / API layer, URL scheme, etc. They should render purely based on their props.

Including the dropdown containers (`PipelinesDropdown`, `ServiceAccountsDropdown`, etc.) causes confusion for new developers contributing to the project as it's not clear when a story should be added, and when it's safe to omit. The stories themselves add little value, being mostly copy-pasted from the same template. They also require additional overhead to enable use of redux etc. in the Storybook.

Remove the following and ensure the Storybook still builds and loads as expected:
- [ ] ClusterTasksDropdown.stories.js
- [ ] NamespacesDropdown.stories.js
- [ ] PipelineResourcesDropdown.stories.js
- [ ] PipelinesDropdown.stories.js
- [ ] ServiceAccountsDropdown.stories.js
- [ ] TasksDropdown.stories.js

The remaining stories for `EventListenerContainer` and `ListPageLayout` should **NOT** be removed at this time.

**Comment by wingyplus** [comment]
@AlanGreene I found during open #2056 that the EventListenerContainer compile error in `Base`, `No ServiceAccount` and `No Service Type` section. I think it's because of the missing `namespace` in `match.params`. But just want to confirm that it's unexpected behaviour, then I'll submit an issue if it's a bug.

<img width="1865" alt="Screen Shot 2564-05-24 at 20 51 06" src="https://user-images.githubusercontent.com/484530/119357469-cf7a0800-bcd1-11eb-8e06-2de9efb8b12c.png">

**Comment by AlanGreene** [comment]
@wingyplus yes that's a bug, thanks for reporting it.

**Comment by wingyplus** [comment]
@AlanGreene Ok. I submitted at #2057 with including bug fix at #2058
