### ISSUE TITLE
Stop exposing k8s API directly

### ISSUE THREAD

**Issue by tmshn** [tektoncd/dashboard#2199]
# Is your feature request related to a problem ?

Currently tekton-dashboard exposes the raw kuberenetes API under `/proxy`. You can fully list, get or update resources as you can do with `kubectl`, but in the name of `tekton-dashboard` service account.

While its permissions are limited by (Cluster)?RoleBindgs (I love the "readonly" version!), I believe some of them are only required by backend (server side). Frontend (client side), and hence dashboard visitors, have too much power. Does it need to list service account? Need to list deployments in all namespaces? Need to see all fields and metadata?

IMO, this is (not urgent but) potential security issue, and a bad practice in web development to be fixed.

# Describe the solution you'd like

Implement dedicated API for dashboard.

I know this requires a bunch of elaboration and introduces complexity, so need to be done in a long term on tradeoff between security.

# Describe alternatives you've considered

# Additional context

**Comment by tmshn** [comment]
Seems related: https://github.com/tektoncd/dashboard/issues/692

**Comment by AlanGreene** [comment]
@tmshn thanks for opening the issue however this is by design and we will be making further improvements to access control in the future.

As you correctly mentioned, https://github.com/tektoncd/dashboard/issues/692 is one of the related issues. The Dashboard itself will not be adding support for authentication / user profiles etc., however it does support passing through headers from an authenticating proxy such as oauth2-proxy which can be deployed in front of the Dashboard. With some additional configuration, the Dashboard could then perform calls to the API server on behalf of the authenticated user. This is being tracked in https://github.com/tektoncd/dashboard/issues/1420. This may work today by granting the Dashboard service account permission to impersonate users but it is not fully tested.

While some of this already works today it's not as fully polished as we would like. Future Dashboard releases will adapt better to the user's permissions, only displaying actions / navigation items the user can actually access instead of presenting an error when they try to perform them. The existing 'read-only' mode will remain, but we will also support custom RBAC settings and react appropriately.

Closing this issue since there are other items already on the roadmap that address the concerns raised and it's currently working as designed.

**Comment by AlanGreene** [comment]
I did spot some unnecessary RBAC settings:
- Services: no longer required, I'll remove this
- ServiceAccounts: should only be required in read-write mode, I'll move them out of the base role and into the patch instead
