### ISSUE TITLE
'Rebuild' button

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#222]
https://github.com/tektoncd/dashboard/issues/108 introduces a means to manually kick off PipelineRuns. Whether triggered by webhook or manually, 'run that build again' is a common need - were those test failures timing related? Was that just a network blip?

A 'rebuild' button needs, 
- the values of any parameters provided to the previous run
- any PipelineResources created for the previous run

In the first instance it may enough to decline a rebuild if PipelineResources have been deleted although we'd obviously rather recreate them if we could. 

Add a 'rebuild' button to the PipelineRun collection and back end logic and support as necessary.

**Comment by a-roberts** [comment]
I'll work on this.

In terms of design here's what I'm thinking - and it's as simple as possible intentionally.

1) Add a "Rebuild" button with a typical "replay" arrow button on the create PipelineRun page
2) Store the PipelineRun API call (literally the request and body) when a build is performed for the manual build case so that the next rebuild click creates the exact same PipelineRun again

In terms of if the build was triggered by a webhook, I'd need to iterate over all PipelineRuns finding the most recent one for the repository - and that can be rebuilt instead (I'll interrogate that PipelineRun and its PipelineResources, ensure they're valid, and make the API request again).

**Comment by a-roberts** [comment]
I've mocked this up today including the API call. 

Unfortunately this isn't going to work for any PipelineRun with the existing createPipelineRun API until we have https://github.com/tektoncd/dashboard/issues/47 implemented which would be awesome to do under https://github.com/tektoncd/experimental/issues/19 - **unless** I implement a new API endpoint, which I'm cool with doing.

Said new API endpoint would simply take json in its request of type `inline` and it would be the full PipelineRun information. I'll then use the Tekton PipelineRun API to create a PipelineRun exactly from this information - which should work unless any resources are no longer available, in which case that's beyond the scope of the rebuild button anyway.

@ncskier FYI, so I'll basically be implementing https://github.com/tektoncd/dashboard/issues/47#issue-432746261 without the PipelineResource creation handling, for this to work.

**Comment by a-roberts** [comment]
This now works on my branch. **I'm currently adding a timestamp to the end of the PipelineRun name to make it unique and clearing the resource version so a new one is generated**. Next step is to add tests and to get the icon actually rendering.

For anyone interested in following you can take a look at my branch [here](https://github.com/a-roberts/dashboard/tree/adam-rebuild-button). I'll report back once I have a PR.

**Comment by a-roberts** [comment]
This has been implemented for a while, waiting on https://github.com/tektoncd/dashboard/pull/259 as it introduces lots of test improvements I need to pick up (otherwise routes_test.go reliably fails for unrelated reasons when I ignore my new rebuild route). Added tests too.

**Comment by a-roberts** [comment]
Merged, closing
