### ISSUE TITLE
Filter PipelineRuns and TaskRuns

### ISSUE THREAD

**Issue by mnuttall** [tektoncd/dashboard#223]
Issue https://github.com/tektoncd/experimental/issues/47 calls for the ability to filter PipelineRuns and TaskRuns by git repository and branch.  This issue calls for a more general ability to filter PipelineRuns and TaskRuns by whatever labels may be on them. 

If started before experimental-47, this issue may render that unnecessary. Either way, please coordinate with anyone that may be working on '47.

**Comment by aunderw** [comment]
Here is a PDF of the search/filter flow:  

[search-scenario-github.pdf](https://github.com/tektoncd/dashboard/files/3398203/search-scenario-github.pdf)

**Comment by jessm12** [comment]
UI issue https://github.com/tektoncd/dashboard/issues/326 in progress

**Comment by a-roberts** [comment]
Let's close this because it's for two separate issues (PipelineRuns and TaskRuns) (I'm going through issues doing a good cleanup).

We have the ability to filter PipelineRuns thanks to work from @jessm12 and I'm going to make one for filtering on TaskRuns, but Icebox that and if anyone wants to pick it up that'd be great but not a big priority for us currently.
