### ISSUE TITLE
Tekton dashboard load too slowly

### ISSUE THREAD

**Issue by love477** [tektoncd/dashboard#2235]
# Is your feature request related to a problem ?
Tekton dashboard pipelineRuns resource plane load too slowly: 20 seconds. The reason for this problem is the api response is too large, almost 50M. Parse so large json is difficulty for browser. 
Have some methods to solve this problem？

**Comment by AlanGreene** [comment]
With responses this large it's not just the Tekton Dashboard that slows down, you'll also see slower responses using kubectl or other tools to inspect resources on the cluster. If possible you could filter the list using a set of known labels that are of interest to you so that only the matching resources are requested. Similarly, ensure you're only viewing resources for the desired namespace by using the namespace dropdown provided in the UI.

See a previous response with links to some relevant discussions and issues at https://github.com/tektoncd/dashboard/issues/1978#issuecomment-796636018. You can also find some discussions about this topic on Slack, e.g. https://tektoncd.slack.com/archives/CHTHGRQBC/p1626688391048400?thread_ts=1626687209.047800&cid=CHTHGRQBC

As described in that issue we have nightly cronjobs on our dogfooding cluster to remove older resources. With ~700 PipelineRuns and ~2000 TaskRuns the pages load in about 3s.
