### ISSUE TITLE
How to use static string value as PipelineResource 

### ISSUE THREAD

**Issue by taechonkim** [tektoncd/dashboard#2259]
# Describe the solution you'd like

I want to use predefined string value as PipelineResource. 
When I trigger Pipeline through tekton dashboard, select predefined string value as PipelineResource, then I want to use these values in PipelineRun. 

For example, PepelineResource named 'resource-1' has value 'string-1'. 

According to [documentation](https://tekton.dev/docs/pipelines/resources/#resource-types), PipelineResource has limited types. 

If there is no way to use string value as PipelineResource, I think it'll be useful feature for users. 

Of course i know there is a way to enter string value in input html element, but it is likely to mistake for users. (e.g. mis-typing...)

# Describe alternatives you've considered

It's okay that way isn't through PipelineResource.
I need to way to deliver predefined string value to PipelineRun, maybe through params... and so on. 
If there is different way to satisfy this requirement, please let me know ;)

**Comment by AlanGreene** [comment]
PipelineResources are deprecated and will be removed from Tekton PIpelines in a future release: https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md

The Dashboard only operates on the features and functionality available through the Tekton CRDs. Parameters are currently either strings or arrays, there's no support for enums for example to provide a predefined selection of options for clients to use: https://tekton.dev/docs/pipelines/tasks/#specifying-parameters

It would be good to start a [discussion in the Pipelines repo](https://github.com/tektoncd/pipeline/discussions) or post on [Slack](https://github.com/tektoncd/community/blob/main/contact.md#slack) to see if others have tried similar things in the past or have suggestions that might be useful.

Closing this issue since there's nothing for the Dashboard to do here at the moment.
