### ISSUE TITLE
Pagination in Dashboard view

### ISSUE THREAD

**Issue by gigatesseract** [tektoncd/dashboard#2263]
# Is your feature request related to a problem ?
We run pipelines on a regular basis and the dashboard becomes unresponsive sometimes when there are a large number of rows to load.

# Describe the solution you'd like
Support for pagination. A given user does not have any requirement to view more than a few pipelineruns at once, in general. 
We can paginate data and lazily load data from the cluster, depending on the requirement.

# Describe alternatives you've considered
None

# Additional context
None

**Comment by AlanGreene** [comment]
Thanks for raising the issue @gigatesseract, this is a popular request we've heard in the past. We agree that it's an important feature but it's not something we're going to implement at this time due to limitations of the Kubernetes API.

See https://github.com/tektoncd/dashboard/issues/1978#issuecomment-796636018 for more related discussion and details about the proposed plan. Closing for now.
