### ISSUE TITLE
Dashboard with OpenShift oauth-proxy?

### ISSUE THREAD

**Issue by disposab1e** [tektoncd/dashboard#2297]
I recognized there is a lot of activity regarding oAuth (and to be honest I read them all) but did not find any solution so far. Is there a chance to get it running. Tried all available switches in oauth-proxy...

I thought the default behaviour is to use the Dashboard ServiceAccount. But whatever I do the ServiceAccount is not used... requests always come as anonymous. Without oauth-proxy the ServiceAccount has the appropriate permissions.

Tekton Dashboard: v0.23.0
OpenShift 4.9
Openshift oauth-proxy 4.9

What I'm doing wrong? Any help is really appreciated. Still using v0.18.0 and everything is fine.

**Comment by AlanGreene** [comment]
You'll need to make sure that the proxy is either NOT forwarding the Authorization header on upstream requests to the Dashboard so that the Dashboard uses its own ServiceAccount, or ensure that the Authorization header contains a valid bearer token for your cluster as that's the value that will be passed to the Kube API server.

https://github.com/tektoncd/dashboard/blob/main/docs/install.md#access-control

I had a look at the OpenShift oauth-proxy docs and don't see any obvious config options that would help here, but I do see a number of open issues with similar requests, including ones specifically related to the Tekton Dashboard, user authorization token for RBAC, etc. There are some suggestions for workarounds provided in the issues and other related discussions but which, if any, may be applicable to your environment depend on your needs and other config.

Closing this for now as there's nothing for the Dashboard to do here. Let me know if you have any other questions or if you do find a solution as it may be helpful for other users.

**Comment by disposab1e** [comment]
@AlanGreene Thx for clarifiaction and having a look at oauth-proxy! Tried all available switches but with no success so far. Posted in openshift-pipelines, let's see. Thx!
