### ISSUE TITLE
Support for re-try option in the pipeline dashboard

### ISSUE THREAD

**Issue by sagaraivale** [tektoncd/dashboard#2826]
# Feature request

There must be an option available to tekton pipeline dashboard side, where we can have re-try for the failed pipeline tasks. Currently we need to re-run the complete pipeline, even if there is single task failed in cascade pipeline workflow.

# Use case

Suppose, we have cascade pipeline, where we have multiple task running in the pipeline, and 9/10, were succeed, However 1 task got failed due to any uncertainty. Now, we need to re-run the whole pipeline to achieve 10/10 results.
  
# Alternatives

We can use re-try mechanism in each task so, that it can may work in 2nd attempt. But, I think there should be an functionality on dashboard side to re-run the failed tasks.
 
# Additional context

Nope.

**Comment by AlanGreene** [comment]
Hi @sagaraivale, thanks for the feature request however this is not something the Tekton Dashboard can add without underlying support from Tekton Pipelines.

Tekton Pipelines currently supports adding a `retries` field on Tasks in a Pipeline: https://tekton.dev/docs/pipelines/pipelines/#using-the-retries-field
> For each `Task` in the `Pipeline`, you can specify the number of times Tekton should retry its execution when it fails.

This is often sufficient for many cases, without the need for on-demand retry of some subset of the Tasks after the PipelineRun has failed.

There is currently no support for partial execution of a Pipeline (e.g. only re-run failed Tasks), but you can find the latest state of this including some design proposals in https://github.com/tektoncd/pipeline/issues/50

Closing since there's nothing for the Dashboard to do here, but feel free to [join us on Slack](https://github.com/tektoncd/community/blob/main/contact.md#slack) or comment on the Pipelines issue I linked to share details of your requirement if they're not already covered by the proposals.
