### ISSUE TITLE
Have Pipelines and Tasks sections also display definitions from remote resolvers, such as git, etc

### ISSUE THREAD

**Issue by woland7** [tektoncd/dashboard#2930]
# Feature request

I think it would be nice to have Pipelines and Tasks definition be displayed on the Dashboard even when their resolver is not of Cluster type. At the moment it just happens for that kind.

# Use case

Even when I use the Git resolver, I'd like to be able to see Pipelines and Tasks from the same Dashboard from where I see the PipelineRuns and the TaskRuns.

# Alternatives

None I can think of.

**Comment by AlanGreene** [comment]
Hi @woland7, thanks for the feature request.

Are you suggesting that the Pipelines and Tasks pages in the Dashboard would show these resources? For example:
![image](https://github.com/tektoncd/dashboard/assets/2829095/81ee27ab-8c98-4f8d-8de8-17bc8c733a37)

If so I don't think this is something we're likely to add.

The Dashboard displays the current state of resources on the cluster. In the case of remote resolvers, the resources are retrieved at runtime and cached in the PipelineRun / TaskRun resources by the Tekton Pipelines controller. No actual Pipeline or Task resource exists on the cluster for the Dashboard to display. The exception to this as you have noted is the cluster resolver as that uses actual resources on the cluster.

Please feel free to reopen if I have misunderstood the request or if you have any suggestions for how this would be achieved. Otherwise closing as not planned for now.

**Comment by woland7** [comment]
@AlanGreene yeah, that's what I meant. The idea was to have to still see the definitions in one point even though they would be retrieved remotely. 

The only workaround I can think of is to somehow keep a synched copy even on the cluster.

Anyway, thanks for the quick response.
