### ISSUE TITLE
ACTION REQUIRED: Changes to pulling Chainguard Images

### ISSUE THREAD

**Issue by chainguard-alerter** [tektoncd/dashboard#2977]
Hey there [Chainguard](https://github.com/chainguard-dev) here.

We noticed that you are using [Chainguard Images](https://github.com/chainguard-images/images), thank you! We wanted to make you aware of an upcoming change that will impact your project.

Starting August 16, 2023 public users will no longer be able to pull images from our registry (cgr.dev/chainguard) by tags other than `latest` or `latest-dev`. Please see [the announcement](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) for more information.

You are currently using the following.

In https://github.com/tektoncd/dashboard/blob/e0923be0ab40331268f5106f883df5d595aaa5ab/src/api/resources/import-resources-pipelinerun.yaml:

- cgr.dev/chainguard/git:2.40

Our goal is to prevent your project from experiencing any disruptions. Please see [the migration guide](https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users) for options.

If there's more we can do to help please reply to this issue or email us at [support@chainguard.dev](mailto:support@chainguard.dev).

Thank you!

**Comment by AlanGreene** [comment]
From the notification:

> Free Images in our Public tier will remain available publicly without requiring authentication:
> - Images tagged :latest and :latest-dev will be available without login required, and will automatically receive all version updates, including major and minor versions.
> - Images pulled by digest (that is, @sha256:...) will be available without logging in, but will not receive any updates or security fixes.
> - SBOMs, signatures and attestations for all Images will be available without logging in.
‍

So it looks like we have 2 options:
- A: switch to `latest` and hope it doesn't introduce breaking changes… 
- B: switch to pulling by digest instead of tag

Currently leaning towards option B.

We'll also need to make patch releases of all Dashboard versions that will still be supported from August 16 to ensure they don't break.

**Comment by imjasonh** [comment]
Hey @AlanGreene, I'm happy to help any way I can with this.

Either option is probably pretty reliable. The `git` image is considered very stable, since it only contains `git` which is itself pretty unlikely to change in large breaking ways (though, never say never 😆). If you choose to go that way I think you'd probably be fine.

Option B is likely to give you the most reliable result, with a bit more work involved to update the digest as new `:latest`s come out. Nothing that can't be automated relatively easily though.

Re: backporting fixes for the image, is there a supported version window for the dashboard project? Do you have an idea how many old releases you'd have to patch?

**Comment by cpanato** [comment]
for option B you can use https://github.com/chainguard-dev/actions/tree/main/digesta-bot :) to update the digests
