### ISSUE TITLE
Tekton Dashboard and Resources Using /v1beta1 API

### ISSUE THREAD

**Issue by ecda909** [tektoncd/dashboard#3686]
# Expected behavior

The Tekton Dashboard should query resources using the `v1beta1` API when the Tekton Pipelines and PipelineRuns are deployed with the `v1beta1` API version, especially when the cluster does not yet support the `v1` API for Tekton resources.

# Actual behavior

The Tekton Dashboard (v0.51.0) attempts to query resources from the `v1` API endpoint (`/apis/tekton.dev/v1`), which results in a `404 (Not Found)` error, as the cluster is only using the `v1beta1` API for Pipelines and PipelineRuns. This causes the dashboard to not display some of the resources correctly, even though they exist under the `v1beta1` API. 

# Steps to reproduce the bug

1. Deploy Tekton Pipelines using the `v1beta1` API.
2. Deploy Tekton Dashboard v0.51.0.
3. Access the Tekton Dashboard to view Pipelines or PipelineRuns.

# Additional info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```sh
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"30+", GitVersion:"v1.30.4-eks-a737599", GitCommit:"96f656cdd7fa6731346f2d92333b713c50434458", GitTreeState:"clean", BuildDate:"2024-08-26T21:27:46Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton versions:

  **Output of `tkn version` or:**
  ```sh
Pipeline version: v0.42.0
Dashboard version: v0.51.0
```

**Dashboard logs**:
```sh
GET http://<endpoint>/apis/tekton.dev/v1/namespaces/tekton-pipelines/pipelines/ 404 (Not Found)
```

**Comment by AlanGreene** [comment]
Thanks for raising an issue @ecda909. You can revert to using the v1beta1 APIs by changing the toggle on the settings page:

<img width="381" alt="image" src="https://github.com/user-attachments/assets/5ac0476b-0b01-4baa-9228-b81c65709a5d">

This toggle was introduced in v0.32 release in January 2023, and has been enabled by default since v0.38 released in July 2023. Disabling the toggle reverts to the v1beta1 APIs for the relevant resources.

Closing as this is working as expected, and user configurable. Please feel free to reopen if I'm missing something, and provide additional information to clarify.

/remove-kind bug

**Comment by AlanGreene** [comment]
> especially when the cluster does not yet support the v1 API for Tekton resources.

> Pipeline version: v0.42.0

Pipelines v0.42 was released in November 2022 and is no longer supported.

From the Dashboard v0.51 release notes:
> This Dashboard release supports Pipelines v0.62.x LTS, and v0.64.x

The last Dashboard release that supported Pipelines v0.42 would have been Dashboard v0.34.

I would strongly suggest updating to a more recent Pipelines release.

**Comment by ecda909** [comment]
Will do. Thank you very much.
