### ISSUE TITLE
Can not logout from the dashboard

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/dashboard#411]
# Expected Behavior
The user should be able to logout from the dashboard.  

# Actual Behavior

There is no UI function to logout from the dashboard.

# Steps to Reproduce the Problem

1. Install the dashboard with login on OpenShift
2. Access to the dashboard and login (OpenShift login screen)
3. There is no way to logout

# Additional Info

I can logout by hitting at 

> https://tekton-dashboard-tekton-pipelines.xx.xx.xx.xx.nip.io/oauth/sign_out

**Comment by mnuttall** [comment]
- We'd like to be able to log out.
- Ideally, the 'log out' option should only be displayed once a user has logged in. This could perhaps be achieved by setting a 'login enabled' environment variable on the dashboard deployment in openshift-tekton-dashboard.yaml.

**Comment by a-roberts** [comment]
For anyone who does pick it up (I was tempted to but doubt I'll have time this week), I figured we'd get an env var when logged in and if set, we'd indeed display the component with the current url + /oauth/sign_out as on the target link. 

I installed on minishift, logged in, I added 
```
	for _, pair := range os.Environ() {
		fmt.Println(pair)
	}
```

in main.go and ko applied, **we don't get any built-in var of use to us, so it would indeed need to be set ourselves  in the yaml file.**

I propose `OPENSHIFT_LOGIN_ENABLED` defaulting to true, indeed set in `openshift-tekton-dashboard.yaml`.

Then we should be able to use `process.env.OPENSHIFT_LOGIN_ENABLED` in our JavaScript code and if set to true, display a new component whose target click event is current url + /oauth/sign_out. We do a lot of current url processing already so that'll be easy.

For testing I propose
- only if env var set, display button
- if button is displayed, ensure correct target url is present

In terms of style, I'm proposing a simple ghost button in the top right with a standard logout icon, as part of the main "container" present on all dashboard pages.

**Comment by a-roberts** [comment]
I'm gonna code what I can and push it to my own branch - maybe it'll be done in time, or anybody else can pick it up and continue in my absence (I'm out next week and we all are tomorrow afternoon).

**Comment by a-roberts** [comment]
Pushed the latest code to my branch linked to in a previous comment, status as follows

- Renders log out button at the top right with a link to /oauth/sign_out (need to test on openshift)
- Boilerplate for test code added
- Detection code todo through index.js: detecting openshift namespace or some other resource

Happy for anyone else to pick this up in my absence please, going back on the backlog

**Comment by a-roberts** [comment]
PR at https://github.com/tektoncd/dashboard/pull/454

**Comment by a-roberts** [comment]
Merged so closing
