### ISSUE TITLE
TaskRun page becomes blank when the namespace or resource are deleted

### ISSUE THREAD

**Issue by ziheng** [tektoncd/dashboard#416]
# Expected Behavior
Task run page should be persisted regardless of the running status

# Actual Behavior
The page becomes to blank

# Steps to Reproduce the Problem

1. Trigger a task run from IBM DevOps pipeline
2. open the view of the task run
3. wait until the run finishes

# Additional Info
![Screenshot 2019-08-09 at 13 31 44](https://user-images.githubusercontent.com/9008867/62779078-0efa4480-baaa-11e9-8849-4fc879057d70.png)

**Comment by AlanGreene** [comment]
The cause here is that the corresponding namespace and resources are deleted after the run completes. Dashboard should be resilient to this and just display a notification that the resource has been deleted / redirect to the PipelineRuns / TaskRuns list instead of falling over and displaying a blank page.
