### ISSUE TITLE
Rebuild button does not provide feedback if an existing notification is on page

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#470]
# Expected Behavior

Clicking the rebuild button for a pipelinerun should trigger a rebuild and provide information/redirection to said pipelinerun

# Actual Behavior

In the case a notification already exists on the page, such as seen in issue #469, clicking rebuild provides absolutely no feedback, even though it has successfully triggered a rebuild.

# Steps to Reproduce the Problem

1. Recreate issue #469
2. Click rebuild

# Additional Info

**Comment by a-roberts** [comment]
Had a quick look through the code while waiting for another PR to be reviewed, some notes before I get a PR created.

https://github.com/tektoncd/dashboard/blob/master/src/containers/PipelineRun/PipelineRun.js#L231 notice here that on getting a PipelineRun error (as in Duane's case as per the linked to issue), we only display this notification and no others. The rebuild button component is still displayed though.

We then have a second return statement, see https://github.com/tektoncd/dashboard/blob/master/src/containers/PipelineRun/PipelineRun.js#L309 which displays the Rebuild button.

So we could either not display the rebuild button at all on the PipelineRun error occurring, or display it but make sure the new notification appears as well. In Duane's scenario, the problem was due to a race condition and so I think the second option is actually desirable.

**Comment by a-roberts** [comment]
To attempt to reproduce this I modified pipeline.go to create PipelineResources incorrectly (incorrect names).

Then on using the import functionality, I see the error, but I never see the Rebuild button for the same error Duane's reporting.

When using the 0.1.1 release image with Tekton 0.5.2 I noticed that for a failed PipelineRun we do see the Rebuild button. So I believe we no longer get the Rebuild button displayed on failing runs anyway and thus it's impossible to enter this state using our latest code.

https://github.com/tektoncd/dashboard/blob/master/src/containers/PipelineRun/PipelineRun.js#L244 this code here is a return with no rebuild component


and later on it's displayed here https://github.com/tektoncd/dashboard/blob/master/src/containers/PipelineRun/PipelineRun.js#L323 (and we can't be returning twice in React can we? So it's one or the other for rendering)

I believe the change is here: https://github.com/tektoncd/dashboard/commit/bcfe703b8af6fd74993d897efb5bf0e93ad6bed6



If we see this again against master let's reopen
