### ISSUE TITLE
Troubleshooting Guide for New Users

### ISSUE THREAD

**Issue by adunderwood** [tektoncd/dashboard#497]
# Expected Behavior

When a user gets an error, there is a guide or document to help them resolve that error.

# Actual Behavior

User gets an error and searches for it on the internet with mixed results. 

# Steps to Reproduce the Problem

1. Hit an error in the product
2. Don't know how to fix it
3. ??

# Additional Info

All error messages in the product to be searchable, either within our own documentation system or on Google or other search engines. If we can create a guide to help resolve common problems post-install I think it could be really helpful since despite our best efforts everything doesn't always go smoothly. If we can get errors recorded with the in-app analytics it would help us build a list of the most common errors. Here are a few troubleshooting scenarios that we could start with:

- Docker installation
- Service account/authentication
- Object not found
- Failure to follow installation instructions

Please feel free to add any other common troubleshooting scenarios as comments to this issue.

**Comment by AlanGreene** [comment]
The dashboard project now provides a series of walkthroughs to guide users in setting up the dashboard for some common scenarios, including setting up a fully working test environment using kind that has Pipelines, Triggers, and Dashboard installed and ready to go.

Since this issue was created we've improved the dashboard's error handling, surfacing more useful information to the user in case of Pipeline / Task failure.

There's also a broader initiative under way across the Tekton projects to gather troubleshooting tips and other content, currently being tracked via https://docs.google.com/document/d/1pe-dNtZ7saZ_cXCTwl7Wq-zo5SDdZDEVCi4QAiszppA/edit
