### ISSUE TITLE
Dashboard doesn't show details/logs of runs if no step names are provided

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/dashboard#709]
# Expected Behavior
I can view logs of task runs associated to pipeline runs.

# Actual Behavior
Dashboard renders an anchor "Not run" for each completed task run related to a pipeline run. 
# Steps to Reproduce the Problem

1. Install the files attached.
2. Create a pipeline run.
3. Click on the pipeline run created above.

# Additional Info
I can describe the resources associated to the pipeline run in question and view their logs through kubectl and tkn, but the dashboard always renders an anchor "Not run" for each task run and nothing else. There are no errors in the Javascript console and all requests have been succeeded, except this one:
```shell
Error
/proxy/apis/route.openshift.io/v1/:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
[files.tar.gz](https://github.com/tektoncd/dashboard/files/3820895/files.tar.gz)

**Comment by alan-ghelardi** [comment]
I've realized that the issue is related to the absence of names on my steps. After assigning names to all steps, the dashboard rendered them successfully.

**Comment by a-roberts** [comment]
Excellent, I'm going to rename this issue then accordingly and it can be picked up as a feature to support - perhaps we say as the step name (if it's not set) - Step 1, 2, 3, 4, etc.

**Comment by alan-ghelardi** [comment]
Looks good to me since the schema doesn't enforce us to provide step names. Thank you so much.

**Comment by AlanGreene** [comment]
Tekton Pipelines already provides a default name for unnamed steps, 'unnamed-1' for example:
![image](https://user-images.githubusercontent.com/2829095/69870786-e8565880-12a8-11ea-8dca-89d143f8e6f6.png)

I think the issue here is that we're only looking for the name in the Task. We should fall back to names from the TaskRun status if not found, but we may have some difficulties matching up the steps since I don't think the step order is guaranteed in the TaskRun status (we've definitely seen steps rendering out of order)...
