### ISSUE TITLE
No error message with valuable information is presented when trying to select a service account for a namespace that does not have service accounts

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#714]
# Expected Behavior
An error message should be displayed when a namespace does not have associated service accounts
# Actual Behavior
When creating a secret, if I select a namespace that does not have associeted service accounts the service account drop-down gets enabled but it displays (in grayed out mode) "Select Service account" and does not provide a message or hint that the selected namespace does not have associated service accounts
# Steps to Reproduce the Problem

1. From the tekton UI select Secrets > Add Secret
2. Select a Namespace that does not have asocciated service accounts (I selected Kabanero, after installing on OpenShift 4.2 and using install-script.sh)
3. try to select a service account

# Additional Info

**Comment by AlanGreene** [comment]
Note for whoever picks this up, the ServiceAccountsDropdown (and other dropdowns) already caters for this empty state: https://alangreene.github.io/dashboard/?path=/story/serviceaccountsdropdown--empty

**Comment by Megan-Wright** [comment]
@rnapoles-tktn I'm struggling to reproduce this... when I install Kabanero on OpenShift and go to create a secret every namespace has associated service accounts. Was there anything else you did to get no service accounts?

**Comment by a-roberts** [comment]
Yeah there's always a service account in every namespace, see `Service Account Controller
Service Account Controller manages ServiceAccount inside namespaces, and ensures a ServiceAccount named “default” exists in every active namespace` from https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

I can't reproduce it either and I'm pretty sure it's not possible unless your service accounts controller's dead (then you've got more problems!).

@rnapoles-tktn if I'm mistaken please reopen this and let us know what you've observed.

With a working install on a healthy cluster I'm convinced this isn't possible and something went wrong at install time (perhaps RBAC and you couldn't get service accounts - and if so that's best suited to a different issue entirely).

**Comment by rnapoles-tktn** [comment]
Agreed, I came across this with a manual setup (my first successful setup)
I could not replicate it with the automated Kabanero setup.
