### ISSUE TITLE
Cannot edit Tekton resources online in dashboard

### ISSUE THREAD

**Issue by anxinyf** [tektoncd/dashboard#718]
# Expected Behavior
For every resource object like Pipeline, PipelineRun, Task, etc. a user can edit it online and then apply it with a button, not only via "Import Tekton resources from repository"

# Actual Behavior
When a user wants to create resources in dashboard, resources can only be created by "Import Tekton resources from repository".

**Comment by AlanGreene** [comment]
@anxinyf thank you for raising this issue, feedback and suggestions are always welcome.

We encourage use of pipeline as code due to its many advantages, including reuse, consistency, repeatability, rollback, etc. In this model, Tekton resources would be defined as a set of YAML files in one or more source control repos and applied in the target cluster either manually using kubectl, using the Import Resources feature in the dashboard, or by some other mechanism (e.g. using Tekton triggers to automatically trigger a PipelineRun that will apply the updated resources).

For this reason, we have chosen not to provide full editing capabilities via the dashboard. We do currently provide UI for creating a very limited set of resource types:
- Secrets: generally secrets would not be stored in source control, and Tekton also expects secrets required by PipelineResources to have specific annotations. Creating these via kubectl can be error prone, so in this case the dashboard UI makes it easier to work with these fields in the correct format expected by Tekton.
- PipelineRuns: we provide the ability to manually create a PipelineRun from the dashboard UI, prompting the user to provide details of any required PipelineResources. This can be helpful for debugging Pipelines during development, or for manually triggering infrequently run Pipelines on demand.

Closing this issue. We can revisit if there's strong demand for more general editing capabilities from the community, but I would definitely recommend adopting a pipeline as code approach for its many benefits.
