### ISSUE TITLE
Dashboard UI Implementation for TaskRuns

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#776]
# Expected Behavior
The portion of the Dashboard UI for Secrets should use design patterns and components for Carbon 10 and reflect the user experience created through collaboration between Development, Design and User Research

# Actual Behavior
The actual behavior is found in the current implementation of the Dashboard UI

# Design Specs:
At the following site, please find these three pages with specs for TaskRuns:
https://kimholmes.github.io/Exported-Specs/TaskRuns1/index.html
Use the left nav to access the following pages:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/21316329/69572006-3ad60300-0f91-11ea-80ec-15501cf26203.png">

**TaskRun Main List View:**
![4  TaskRuns](https://user-images.githubusercontent.com/21316329/69572584-6dccc680-0f92-11ea-88bf-bac8d878e45e.png)

**TaskRun Row Selected:**
![5  TaskRuns_Selected](https://user-images.githubusercontent.com/21316329/69572622-83da8700-0f92-11ea-820f-d5ff0e899388.png)

**TaskRun Interactive Diagram:**
*Note that the interactive diagram uses the same specs as the PipelineRun diagram:
https://github.com/tektoncd/dashboard/issues/675
![6  TaskRuns_Topology](https://user-images.githubusercontent.com/21316329/69572633-8d63ef00-0f92-11ea-9e79-a1b57fea59ed.png)

**Comment by AlanGreene** [comment]
Is there much value in including the diagram for a TaskRun? It will only have a flat list of steps in the same order as the list on the left. The nodes on the diagram won't expand as there's no child content to display.

Would this also potentially cause confusion for users that here we're rendering steps the same way we render TaskRuns on the PipelineRun diagram?

**Comment by kimholmes** [comment]
@AlanGreene I was under the assumption that we were rendering steps the same way we render them in TaskRuns on a PipelineRun. How is this different? Wouldn't the user be able to expand the Tasks and view the Steps inside?
Now that I've asked all these questions, I think it's always a positive to simplify the experience. But if we remove this diagram, would the TaskRuns be linked from the list page? And if so, what would it link to?

**Comment by AlanGreene** [comment]
If we were to render TaskRuns and steps the same way here as we do on the PipelineRun diagram we would always have exactly 3 nodes on the diagram (start, TaskRun, end) and it would look something like this:
![image](https://user-images.githubusercontent.com/2829095/70258374-0b3eac00-1784-11ea-90e4-bd5a3037fdf4.png)

There would always be a single node between start and end representing the TaskRun. When expanded it would show the list of steps. Clicking on a step on the diagram would expand the corresponding accordion section on the left. Expanding / collapsing the TaskRun likely wouldn't cause any change on the left as we already show the list of steps there. It might even make sense to always have it expanded and remove the chevron.

However, in the screenshot in the description we have a separate node on the diagram for each step, and it looks like those nodes can be expanded (chevron to the right of the name). What additional content would be displayed on the diagram in this case? Steps don't have children since they're the smallest building block.

Regardless of whether we have a single node for the TaskRun or split it out to one node per step, the graph for a TaskRun will always be a straight line from start to end. Since the list on the left already gives us this same flat list, is there any benefit to having the graph on the same page?

**Comment by kimholmes** [comment]
@AlanGreene It does make sense. I see what you mean about removing the chevron but then I wonder if we shouldn't just keep it for consistency.
You're right, we didn't give a proper representation of the diagram in the design. The two nodes are intended to be tasks but that doesn't make sense if we're in the context of a taskRun. So, you are correct!
If we decide to keep this entire view, I think we should include the diagram, just for consistency sake. But if you think this whole diagram/accordion view is not beneficial to the user, then maybe we rethink the whole thing. But that would probably fall after the new year.

**Comment by AlanGreene** [comment]
Sounds good, thanks.

**Comment by AlanGreene** [comment]
Related https://github.com/tektoncd/dashboard/issues/762

**Comment by AlanGreene** [comment]
Only remaining item here is the visualisation which is being tracked in #675
