### ISSUE TITLE
PipelineRun timeout message isn't formatted on display in table

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#800]
See 
![image](https://user-images.githubusercontent.com/12814972/70137755-9afe3080-1686-11ea-86e6-be6ca1699584.png)

Reproduce is to create a PipelineRun that times out

**Comment by AlanGreene** [comment]
@a-roberts what's the issue here, the `"&Duration{Duration:1h0m0s,}"` piece? The status message comes from the resource directly, we don't manipulate it in any way, so this is the actual content being set by Tekton Pipeline.

**Comment by a-roberts** [comment]
> @a-roberts what's the issue here, the `"&Duration{Duration:1h0m0s,}"` piece? The status message comes from the resource directly, we don't manipulate it in any way, so this is the actual content being set by Tekton Pipeline.

Exactly, it'd be great to capture timeout events and display a custom message instead e.g. "failed to finish within one hour, 30 seconds" for example - instead of displaying the unmanipulated info.

So what I'm suggesting is essentially grabbing that status and manipulating it if it's a timeout - I realise that's a bit awkward mind you come to think of it (I'm not a fan of grabbing what's over the websocket as it comes in all the time and then fiddling with it if it looks a certain way). What do you think - worthwhile?

**Comment by AlanGreene** [comment]
If the data (probably just the timeout value) is available in a structured format in the status or somewhere else we can easily grab we could do a better job of formatting it, however I'd be reluctant to start trying string manipulation. I wouldn't consider the message content part of the Tekton Pipeline APIs, and some of the values are actually from a level deeper still, from kubernetes itself.

One idea I've been toying with (just in my head so far) is changing how we display the status on these tables. Instead of putting the full status message (which is quite long in some cases) into the table we could use the status value instead, maybe keeping the full text as a tooltip or something.

So this would be one of the values we see displayed in the header on the run details pages, e.g. `PipelineRunCancelled`
![image](https://user-images.githubusercontent.com/2829095/70161083-6ce31580-16b3-11ea-84a8-d496d81f5037.png)

I might try that out and share a demo environment for folks to try out, see if it's an improvement.

That change on its own doesn't resolve the issue, but might give us a better opportunity to handle things more cleanly.

**Comment by AlanGreene** [comment]
Draft PR showing the status values on the tables as described above: https://github.com/tektoncd/dashboard/pull/836
Example of how this could look: 
![image](https://user-images.githubusercontent.com/2829095/71667680-0e669100-2d5e-11ea-8927-ad95fa2d9e3d.png)

**Comment by AlanGreene** [comment]
Timeout message fixed in Pipelines https://github.com/tektoncd/pipeline/issues/2023
