### ISSUE TITLE
Move deps into dev deps for package.json

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#82]
In our package.json there's a lot that looks to me like dev dependencies (babel, webpack, eslint etc) - so this issue is to take a look at our package.json and see what can be classified as a dev dependency versus a regular one.

As a useful ref: https://github.com/CloudNativeJS/mern-workshop/blob/master/frontend/package.json

**Comment by AlanGreene** [comment]
Typically the devDependencies separation is more useful for libraries consumed by others so their build / test tooling doesn't get installed when not needed. Since we're running `npm install` on this project directly they'll all get installed anyway.

However I can see an argument for keeping the separation, to make it clear what's used at dev time vs. potentially contributing content to the build output.

/assign
