### ISSUE TITLE
New storybook components

### ISSUE THREAD

**Issue by carrenelloyd** [tektoncd/dashboard#846]
# Expected Behavior
The current storybook should have all of the custom components and patterns Tekton needs in the application so that it complies with Carbon standards. This list should be expected to grow as the application progresses over time. 

# Actual Behavior
The current storybook only has a portion of the components and patterns needed in the product 

# Steps to Reproduce the Problem

Here are some ideas for patterns in the Storybook:
1. Page Title Header: background color, page title, breadcrumbs, buttons, spacing, etc
2. YAML file component
3. Logs component 
4. Tabbed Header and background 
5. Forms and Create new flow (Secrets, Annotation, Service Accounts, etc)
6. Logs
7. Empty State (Carbon had a pattern, but not a component) 
8. Lists or metadata (not sure what to call this one)

# Additional Info (Examples)

### Page title Header
example 1
![image](https://user-images.githubusercontent.com/53481064/71024864-db709c00-20d3-11ea-8d65-9923e783bd6d.png)
example 2 - We may or may not decide to build the Filter component into the Page Title Header.
![image](https://user-images.githubusercontent.com/53481064/71024878-e9262180-20d3-11ea-8e8f-4607ade071fb.png)

### Forms/ Creation Flows
This flow is different from other pages in that it has a $ui-background of color Gray 10. A Page Title isn't present, nor is a Search. This is essentially a mode the user goes into to "create". 
![image](https://user-images.githubusercontent.com/53481064/71025133-72d5ef00-20d4-11ea-9c17-c7b24d67e930.png)

![image](https://user-images.githubusercontent.com/53481064/71025159-7c5f5700-20d4-11ea-9d65-6ece282e9a27.png)

![image](https://user-images.githubusercontent.com/53481064/71025176-841efb80-20d4-11ea-895e-fc08ee2dafcf.png)

### Empty State
![image](https://user-images.githubusercontent.com/53481064/71025259-a87ad800-20d4-11ea-97a9-8dbd487865eb.png)

### Metadata
![image](https://user-images.githubusercontent.com/53481064/71025340-d7914980-20d4-11ea-9fbc-b66f4ebe19cc.png)

### **Tabbed Area**
This could be a variation of the Page Title Header. The difference is the background-color and the presence of a tab
![image](https://user-images.githubusercontent.com/53481064/71024910-f7743d80-20d3-11ea-9673-19b4353544d6.png)

![image](https://user-images.githubusercontent.com/53481064/71024969-1672cf80-20d4-11ea-8745-d4a3d50eb935.png)

### YAML 
![image](https://user-images.githubusercontent.com/53481064/71024997-268aaf00-20d4-11ea-9ef1-8b1b12289e61.png)

### Logs 
![image](https://user-images.githubusercontent.com/53481064/71025054-4a4df500-20d4-11ea-9efe-e23d40fb4cb3.png)

**Comment by AlanGreene** [comment]
- Page Title Header - should be extracted from ResourceDetails and also consider https://github.com/tektoncd/dashboard/issues/805
- YAML file component - we have a `ViewYAML` component that used for the YAML tab on ResourceDetails as well as some other locations in the UI. Further enhancements to this could include syntax highlighting.
- Logs component - our logs component has some known issues with very large logs and also with long line lengths. We've addressed some of the performance issues, but these are in conflict with other requests such as allowing line wrapping, following new logs, displaying logs for multiple steps / Tasks in parallel, etc. so need to revisit this
- Tabbed Header and background - mostly covered by ResourceDetails
- Forms and Create new flow (Secrets, Annotation, Service Accounts, etc) - we have components for parts of these but they're not easily reusable due to logic / data being tightly coupled with the UI. Some efforts have been made to separate these but it hasn't been a high priority.
- Empty State - Cloud PAL builds on the Carbon pattern and provides a component but this is not consumable outside IBM. We could use the guidelines to build our own component and replace our various empty states with this single consistent UI.
- Lists or metadata
  - Lists: we don't have a single component covering the entire list view, but we do have a small number of reusable components that are easily composed to produce it, the general form is:
     ```
     <Header />
     <LabelFilter />
     <DataTableWrapper />
     ```
      where `DataTableWrapper` would be a container with the resource-specific APIs / logic required to produce the desired data, and would then use a Carbon DataTable to display this
  - metadata: ResourceDetails provides the 'Details' tab showing basic metadata common to all resources, i.e. name, namespace (optional), description (optional), labels, created time, as well as resource-specific fields such as the `type` field for `PipelineResource`s

**Comment by AlanGreene** [comment]
Closing since we have pure UI components (included in the storybook) for the pieces that make sense, and relatively simple combinations of those components + some additional wiring for the remainder.

/close
