### ISSUE TITLE
Feature Request: Validate git/docker secret in UI

### ISSUE THREAD

**Issue by dacleyra** [tektoncd/dashboard#892]
Consider a validation stage to the git/docker secret creation in the dashboard ui.

As to prevent later failure in pipeline stage during pull/push due to invalid credential.

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/issues/538

**Comment by AlanGreene** [comment]
Closing this, also see #538 for related info.

We now surface more useful errors in case of a task relying on one of these secrets failing.

Also worth mentioning that PipelineResources are remaining in alpha for now, and may be removed / rewritten in a future Tekton release. The alternative approach using Tasks does not use the annotations added to Secrets created by the Dashboard, so further expanding this UI doesn't make sense right now.

I'd be happy to revisit if someone proposes an approach that wouldn't require the dashboard itself to implement the validation since we should work with any supported service provider, or once the future of PipelineResources is clearer.
