### ISSUE TITLE
Dropdown fields use DIV tag instead of SELECT causing automation to throw UnexpectedTagNameException 

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#903]
Problem:
All Dropdown fields use DIV tag instead of SELECT. This prevents the selenium automation to click the elements when trying to gain access to them by ID or xpath, and when using the SEELCT selenium class I get:
UnexpectedTagNameException: Element should have been "select" but was "div"
The dropdown is implemented this way:
![image.png](https://images.zenhubusercontent.com/5db346d5b0111c0001df287a/2784b3a8-db57-4386-9f99-f22b86feca0d)

Expected:
Follow carbon component spec:
![image.png](https://images.zenhubusercontent.com/5db346d5b0111c0001df287a/e37f701c-78ae-430d-827c-fcd472909723)

**Comment by AlanGreene** [comment]
This looks like code from the webhooks-extension: https://github.com/tektoncd/experimental/blob/b0a597ed18ed7cfda6c16488461c33675dd269b1/webhooks-extension/src/components/WebhookCreate/WebhookCreate.js

@rnapoles-tktn if you can confirm this is for the webhooks-extension we can get the issue moved over to the tektoncd/experimental repo

**Comment by AlanGreene** [comment]
Most of the common dropdowns (e.g. namespace) used in the dashboard UI are based on the Carbon Dropdown component. You can find details here: http://react.carbondesignsystem.com/?path=/story/dropdown--default

If your automation is expecting a HTML select element then that would explain why you're running into an unexpected error.

Ideally the automation would interact with the UI as a real user does, using user-visible content (labels, placeholder text, tooltip content, etc.) rather than relying on a specific DOM structure or hardcoded id. This is the approach we adopt in our own unit and integration tests too, reducing brittleness and churn in the tests as components are updated / swapped out.
