### ISSUE TITLE
Assess the move to Triggers 0.2 (Dashboard)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#918]
As an end user I expect to be able to use the Tekton Dashboard with Triggers 0.2. When using the webhooks extension there's a fundamental flaw with our architecture too - a user can't create more than eight webhooks or they'll get an admission webhook timeout error (more details at https://github.com/tektoncd/triggers/issues/356)

Related webhooks issue https://github.com/tektoncd/experimental/issues/431

**Comment by a-roberts** [comment]
Issues found when installing Triggers 0.2 after having the dashboard and extension and Triggers 0.1 already installed:

1) No displaying of Trigger resources

Failed to load resource: the server responded with a status of 404 (Not Found)
https://tekton-dashboard-tekton-pipelines.apps.ridgy.os.fyre.ibm.com/proxy/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/eventlisteners.tekton.dev

2) Can't create webhooks

```
Error:

Failed to create webhook, error returned was : error creating webhook due to error creating eventlistener. Error was: Internal error occurred: admission webhook "triggers-webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "header"
```

**Comment by a-roberts** [comment]
Fix for trigger resource displaying on OpenShift https://github.com/tektoncd/dashboard/pull/920

**Comment by a-roberts** [comment]
@ncskier and I have been contemplating and testing this, so with an EventListener made with 0.1, and then with Triggers 0.2 installed, everything appears great - including TriggerTemplates and TriggerBindings.

We think there'll be a problem when we have multiple interceptors (in that they won't be picked up from the array, as you can now have multiple) and the same principle applies for bindings (of which there can now be multiple).

**Comment by a-roberts** [comment]
@kimholmes hey Kim, here's the item for assessing the Triggers 0.2 move - so once it's done, please work with @kimholmes and co on progressing this item forwards

We're thinking of doing the move to Triggers 0.2 *after* we move to Pipelines 0.10.

**Comment by ncskier** [comment]
I think Adam pretty much covered everything, but here's a summary so we can view everything at once (let me know if I missed anything):

### TriggerTemplate list & details pages
No change

### TriggerBinding list & details pages
No change

### EventListener details page
1. Multiple _interceptors_
EventListener triggers can now have multiple _interceptors_ instead of just one. So, we must display this list of _interceptors_.
2. Multiple _bindings_
EventListener triggers can now have multiple _bindings_ instead of just one. So, we must display this list of _bindings_.
3. No more _params_
EventListener triggers no longer have _params_. So, we must no longer display the list of params.

### EventListener list page
No change

**Comment by a-roberts** [comment]
Assessments done so I'll make follow-up issue(s) for getting it in, keeping https://github.com/tektoncd/dashboard/issues/937 in mind
