### ISSUE TITLE
Misc. Front End Development Specs for Dashboard Designs

### ISSUE THREAD

**Issue by kimholmes** [tektoncd/dashboard#966]
This issue should reside under the following Epic:
https://github.com/tektoncd/dashboard/issues/965

- [x] 1. ~~Remove blue background~~ Tracked in https://github.com/tektoncd/dashboard/issues/803
  <details>

  **Expected behavior** - no blue background
  ![NOblueBackground](https://user-images.githubusercontent.com/21316329/73215862-e41caf00-4122-11ea-8b83-bbb37d4662af.png)

  **Actual behavior**
  ![blueBackground](https://user-images.githubusercontent.com/21316329/73216011-3231b280-4123-11ea-946f-73dd7a780c47.png)
  </details>

- [ ] 2. Filter pill appearing when linking to PLRs filtered by Pipeline
  <details>

  **Expected behavior**
  The filter remains empty since the user never engaged with it.

  **Actual behavior**
  A search term gets added to the filter without the user's interaction.
  ![Filter_pipeline](https://user-images.githubusercontent.com/21316329/73216390-eb908800-4123-11ea-8339-b6df8a694a90.png)
  </details>

- [ ] 3. Make tables consistent per design. Remove ellipse action menu and move actions into header per Carbon table component 
  <details>

  **Expected behavior**
  Actions are stored in the header and activated when a row is selected
  ![tableCorrect](https://user-images.githubusercontent.com/21316329/73217212-7e7df200-4125-11ea-8a83-494359ea8cff.png)

  **Actual behavior**
  The table stores actions in an "actions ellipse" at the end of the rows instead of using the Carbon header that utilizes checkboxes and buttons.
  ![table_inconsistent](https://user-images.githubusercontent.com/21316329/73216827-ba648780-4124-11ea-9009-10f4b2965a3f.png)

  ~~The Create buttons on the PipelineRuns and PipelineResources pages should also be moved to the Table header as on the Secrets page.~~ Done
  </details>

- [x] 4. Update Filter design throughout
  <details>

  **Expected behavior**
  ![FilterSpec1](https://user-images.githubusercontent.com/21316329/73757180-d4aaf080-4736-11ea-9747-e1c3df7e0443.png)
  ![FilterSpec2](https://user-images.githubusercontent.com/21316329/73757186-d7a5e100-4736-11ea-8e49-6a7e9a8a6fb6.png)

  **Actual behavior**
  <img width="952" alt="image" src="https://user-images.githubusercontent.com/21316329/73757341-1c317c80-4737-11ea-9cbb-9cdb6fb5c2d1.png">
  </details>

- [ ] 5. Update "Create PipelineRun" UI. Move from modal window to full page for better user experience and consistency with the rest of the dashboard.
  <details>
  
  **Expected behavior**
  ![694b9800-4112-11ea-8724-3f98d5a4b8d7](https://user-images.githubusercontent.com/21316329/73960667-520e6680-48d9-11ea-89f4-5b797ad45ce8.png)
  ![5fcc2b00-4126-11ea-8bdc-b0fb68961fb1](https://user-images.githubusercontent.com/21316329/73960675-55a1ed80-48d9-11ea-802e-8b38416b915e.png)

  **Actual behavior**
  ![53ee7003-440c-4efe-a1d7-cc6e10b25977](https://user-images.githubusercontent.com/21316329/73960760-710cf880-48d9-11ea-99a3-ed2876808ce5.png)
  </details>

**Comment by AlanGreene** [comment]
1. Should this wait for the [rail](https://github.com/tektoncd/dashboard/issues/803) or do we want to do something tactical in the short term? If we just remove the blue and leave the side nav as-is it looks incomplete and there's no separation between it and the content.
  ![image](https://user-images.githubusercontent.com/2829095/73218771-86a05680-4152-11ea-8e53-f8f8b35fe110.png)

2. Adding/removing filters updates the URL so the user can always share/bookmark that URL to return to the filtered list they're currently viewing (selected namespace + label filters). It's important to keep this functionality.

   The connection between the URL and the filters also works in the opposite direction, which is what you're seeing here. When we link to a filtered view (e.g. from the Pipelines table), those filters are included in the URL. The label filter component reacts to the presence of the filters in the URL and displays the corresponding tags for consistency.

   If we remove this second piece of behaviour, a user would be presented with two slightly different views of the same data (one showing the filter tags, the other not), and it wouldn't be obvious that they're both actually filtered in the same way.

   As we discussed last week, does this need to be part of a bigger change? i.e. introducing the missing detail pages for Pipeline, Task, etc., and having a more explicit action on the Pipelines / Tasks lists to view a filtered list of runs for the selected item? This way it shouldn't be a surprise to the user that the filter is pre-populated when they land on the runs list.

3. For actions such as re-running a PipelineRun where a user is most likely to only select a single item are we OK with keeping an inline action on the row using an icon instead of the overflow menu? https://carbondesignsystem.com/components/data-table/usage#inline-actions

**Comment by kimholmes** [comment]
@AlanGreene I understand what you mean about needing the URL with the filter. My concern is whether or not the user will actually even know that it's there. I'm afraid if we user tested this, the user wouldn't even be aware that this function exists. It's a bit "under the covers." 

Yes, I think it's totally fine to put the re-run function on the table row for the PLRs. Since it's only one action, I think we should use a simple icon with a column header instead of hiding it in that action dropdown menu.

**Comment by AlanGreene** [comment]
For 3. we should also include moving the Create buttons to the table header instead of beside the filter as discussed at our last design office hours. Updated the description above.

**Comment by kimholmes** [comment]
Yes! The design for these pages are spec'ed out in the following issues:
https://github.com/tektoncd/dashboard/issues/727
https://kimholmes.github.io/Exported-Specs/Secrets/Secrets_Main/

**Comment by kimholmes** [comment]
@AlanGreene @carlos-logro FYI - Just added the "Create PipelineRun" panel to this issue. The spec is to move it to a full page. Thanks.

**Comment by AlanGreene** [comment]
Batch delete for PipelineRuns and TaskRuns will be added as part of https://github.com/tektoncd/dashboard/issues/1752, this addresses part of item 3.

**Comment by AlanGreene** [comment]
Tracking 5. in https://github.com/tektoncd/dashboard/issues/1791

**Comment by AlanGreene** [comment]
Similar issue for Create TaskRun since we didn't have that functionality when 5. was written: https://github.com/tektoncd/dashboard/issues/1792

**Comment by AlanGreene** [comment]
Closing as the remaining items are already tracked in other issues linked above.

/close
