### ISSUE TITLE
Update page header styles

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#976]
For consistency and to move us closer to the desired design, we should update the global styles for the h1 page header tag.

![image](https://user-images.githubusercontent.com/2829095/73355416-054ede00-4290-11ea-9833-a7d3c4330098.png)

https://ibm.invisionapp.com/share/MPNZNGNZJ3E

This translates as:
- [x] `$layout-02` (24px) margin from nav header to title (padding-top on bx--content)
- [x] `h1 { @include type-style(productive-heading-04) }`
- [x] `$layout-02` (24px) margin from title to filter
- [ ] `$layout-04` (48px) margin from filter to create button

**Comment by AlanGreene** [comment]
@carrenelloyd I have a PR open with most of the header changes you requested.

The one piece it doesn't include is the spacing between the filter and the button. I think this is right but just wanted to confirm before I change it, should the margin between the filter input and the create button still be 48px when the filter tags are present (unless they wrap onto a new line of course)?

![image](https://user-images.githubusercontent.com/2829095/73355740-b5bce200-4290-11ea-8753-359c28663a8a.png)
![image](https://user-images.githubusercontent.com/2829095/73356060-60cd9b80-4291-11ea-9f16-4d7a1b271aec.png)

It's currently some odd fraction around 53 - 54px and it'll need a little extra work to clean up the code and get it right.

**Comment by carrenelloyd** [comment]
@AlanGreene Yes, that's correct 48 px. The filter "pillows" can go in the 48 px space. (see screen below)

I know the implementation and the high-fis don't align exactly at the moment, but in our meeting coming up this Thursday, we can discuss the strategy for the Filter moving forward. I know Carbon has a filter similar the one in our mockups that is due to come out shortly. 

It would also be nice to remove the word "Filters:" and change the pillows from the blue Tag component to use the black pillow UI—so it looks less like a Tag.

![image](https://user-images.githubusercontent.com/53481064/73362660-3d94f300-4275-11ea-902b-9838bf4efa63.png)
